name: cp949_codec
description: The best package for cp949 decoding/encoding. support null-safety, less memory comsumption. include examples and tests
version: 0.1.0
repository: https://github.com/letyletylety/cp949_codec

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
dev_dependencies:
  test:

