name: cp949_codec
description: cp949 decoding/encoding
version: 0.0.1
homepage:
authors:
  - lety

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: