name: cp949_codec
description: cp949 decoding/encoding
version: 0.0.2
repository: https://github.com/letyletylety/cp949_codec

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
dev_dependencies:
  test:

